### ISSUE TITLE
Fetch and display job result on (angular)

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl-ng#4]
**Task 5**:

- [ ] API call to fetch job results from backend
- [ ] The user should be able to easily fetch and view the report for any particular job
- [ ] Implement a similar tabular view for file analyzers based results
- [ ] Write modular and reusable code so one can reuse components between the file and observable result viewers.
